app_ghound/urls.py
#new file

from django.contrib import admin
from django.urls import path, include
from . import views
from .apps import AppGhoundConfig

app_name = "app_ghound"

urlpatterns = [
    path('', views.main, name='root'),
    path('app_ghound/', views.main, name='app_ghound'),   
    path("users/", include("users.urls"))
]

g_hound/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

ghound/urls.py
"""
URL configuration for ghound project.

The `urlpatterns` list routes URLs to views. For more information please see:
    https://docs.djangoproject.com/en/5.0/topics/http/urls/
Examples:
Function views
    1. Add an import:  from my_app import views
    2. Add a URL to urlpatterns:  path('', views.home, name='home')
Class-based views
    1. Add an import:  from other_app.views import Home
    2. Add a URL to urlpatterns:  path('', Home.as_view(), name='home')
Including another URLconf
    1. Import the include() function: from django.urls import include, path
    2. Add a URL to urlpatterns:  path('blog/', include('blog.urls'))
"""
from django.contrib import admin
from django.urls import path, include #+include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("app_ghound.urls")),
    path("users/", include('users.urls', namespace='users'))
]

users/urls.py
from django.contrib import admin
from django.urls import path, include 
from . import views
from django.contrib.auth.views import LoginView, LogoutView
from .forms import LoginForm
from .views import RegisterViews

app_name = "users"

urlpatterns = [
    path('signup/', RegisterViews.as_view(), name="register"), 
    path('login/', LoginView.as_view(template_name='users/login.html', authentication_form=LoginForm,
                                      redirect_authenticated_user=True), name='login'),    
    path('logout/', LogoutView.as_view(template_name='users/logout.html'), name='logout')    
]

app_ghound/models.py
from django.db import models

# Create your models here.

users/models.py
from django.db import models

# Create your models here.

users/forms.py
#all file new 4
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.forms import CharField, TextInput, EmailField, EmailInput, PasswordInput


class RegisterForm(UserCreationForm):
    username = CharField(max_length=100,required=True, widget=TextInput(attrs={"class": "form-control"}))
    first_name = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    last_name = CharField(max_length=150, widget=TextInput(attrs={"class": "form-control"}))
    email = EmailField(max_length=150,required=True, widget=EmailInput(attrs={"class": "form-control"}))
    password1 = CharField(max_length=20, min_length=4, required=True, widget=PasswordInput(attrs={"class": "form-control"}))
    password2 = CharField(max_length=20, min_length=4, required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username","first_name","last_name","email","password1","password2")


class LoginForm(AuthenticationForm):
    username = CharField(max_length=100,required=True, widget=TextInput(attrs={"class": "form-control"}))
    password = CharField(max_length=20, min_length=4, required=True, widget=PasswordInput(attrs={"class": "form-control"}))

    class Meta:
        model = User
        fields = ("username","password")

app_ghound/views.py
from django.shortcuts import render

# Create your views here.
def main(request):
    return render(request, 'app_ghound/index.html', context={"test":"Test!"})

users/views.py
from django.shortcuts import render, redirect
from django.views import View
from django.contrib import messages
from django.contrib.auth.views import LogoutView as DjangoLogoutView
from django.views.decorators.csrf import csrf_protect
from django.utils.decorators import method_decorator
from django.contrib.auth import logout

from .forms import RegisterForm

class RegisterViews(View):
    form_class = RegisterForm
    template_name = "users/signup.html"

    def dispatch(self, request, *args, **kwargs):
        if request.user.is_authenticated:
            return redirect(to="app_ghound:root")
        return super(RegisterViews, self).dispatch(request, *args, **kwargs)

    def get(self, request):
        return render(request, self.template_name, {"form":self.form_class})
    
    #реєстрація
    def post(self, request):
        form = self.form_class(request.POST)
        print(form)
        if form.is_valid():
            form.save()
            username = form.cleaned_data["username"]
            messages.success(request, f"Вітаю {username}! Ваш акаунт успішно створений ")
            return redirect(to="users:login")
        return render(request, self.template_name, {"form": form})

app_ghound/templates/app_ghound/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
    {% load static %}
    <link rel="stylesheet" href="{% static 'app_ghound/style.css' %}">

    <title>Document</title>
</head>
<body>
<div class="container">
    <div class="row header-box pt-3 mb-3">
        <div class="col-md-8">
            <h1>
                <a href="/" style="text-decoration: none">App Ghound</a>
            </h1>
        </div>
        <div class="col-md-4">
            <p>
                {% if user.is_authenticated%}
                <form method="post" action="{% url 'users:logout' %}">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary">Logout</button>
                </form>
                {% else %}
                <a href="{% url 'users:register' %}" class="btn btn-primary">SignUp</a>
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login</a>
                {% endif %}                             
                
    </p>

            </p>
        </div>
    </div>


    {% block content %} {% endblock %}

</div>
</body>
</html>

app_ghound/templates/app_ghound/index.html
{% extends "app_ghound/base.html" %}

{% block content %}
<h1> G Hound</h1>
{% endblock %}

users/templates/users/login.html
{% extends "app_ghound/base.html" %}

{% block content %}
<h1>Login</h1>

<!-- Виводимо флеш-сповіщення-->
{% if messages %}
{% for message in messages %}
<div {% if message.tags %} class="alert alert-{{message.tags}}" {% endif %} role="alert">
    {{message}}
</div>
{% endfor %}
{% endif %}

<!--Обробляємо помилки форми, які не відносяться до полів -->
{% if form.errors %}
<div class="alert alert-danger" role="alert">
    {{form.non_field_errors}}
</div>
{% endif %}

<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password}}
        </div>
        <span>{{form.errors.password}}</span>
    </div>

    <button type="submit" class="btn btn-primary">Login</button>
</form>

{% endblock%}

users/templates/users/logout.html
{% extends "app_ghound/base.html" %}

{% block content %}
    <h1>Бувайте!</h1>

{% endblock %}

users/templates/users/signup.html
{% extends "app_ghound/base.html" %}

{% block content %}
<h1>SignUp</h1>
<form method="post">
    {% csrf_token %}
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Username</label>
            {{form.username}}
        </div>
        <span>{{form.errors.username}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">First Name</label>
            {{form.first_name}}
        </div>
        <span>{{form.errors.first_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Last Name</label>
            {{form.last_name}}
        </div>
        <span>{{form.errors.last_name}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Email</label>
            {{form.email}}
        </div>
        <span>{{form.errors.email}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Password</label>
            {{form.password1}}
        </div>
        <span>{{form.errors.password1}}</span>
    </div>
    <div class="form-row">
        <div class="mb-3">
            <label class="form-label">Confirm password</label>
            {{form.password2}}
        </div>
        <span>{{form.errors.password2}}</span>
    </div>
    <button type="submit" class="btn btn-primary">Sign Up</button>
</form>

{% endblock%}